# Site settings
title: Erin K. Meyer
email: erinkmeyer@sbcglobal.net
description: > # this means to ignore newlines until "baseurl:"
  Jekyll Theme Demo
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://ekmeyer.github.io" # the base hostname & protocol for your site
twitter_username: erin_k_meyer
github_username: ekmeyer

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md


